config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :missions, only:[:show, :index] do
    resources :bookings, only:[:create]
  end

  get "/dashboard", to: "users#dashboard"
  namespace :dashboard do
    resources :bookings, only: :show do
      member do
        patch "cancel"
      end
    end
  end


  # resource :dashboard, only: :show
  # => GET   /dashboard(.:format)   dashboards#show

  # resources :bookings, only: []

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :mission

  validates :status, presence: true
  # validates :number_volunteers, presence: true

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new

    @booking.user = current_user

    @mission = Mission.find(params[:mission_id])
    @booking.mission = @mission

    if @booking.save!
      redirect_to dashboard_path(booking_created: true)
    else
      redirect_to mission_path(@mission)
    end
    # booking = table de jointuer donc associé à un user + à une mission
  end
end

app/controllers/dashboard/bookings_controller.rb
module Dashboard
  class BookingsController < ApplicationController
    def show
      @booking = Booking.find(params[:id])
      @address = @booking.mission.address
      @partner = @booking.mission.partner

      # @markers = [{ lng: @booking.mission.longitude, lat: @booking.mission.latitude}]
      @markers = [
      {
        lng: @booking.mission.longitude,
        lat: @booking.mission.latitude,
        infoWindow: render_to_string(partial: "missions/info_window", locals: { mission: @booking.mission }),
        imageUrl: helpers.asset_url("location-pin-yellow.png")
      }
    ]
    end

    def cancel
      @booking = Booking.find(params[:id])
      @booking.status = "declined"

      @booking.save
      redirect_to dashboard_path
    end
  end
end

app/views/dashboard/bookings/show.html.erb
<!-- CARDS -->
<div class ="container flex-container">
  <div class="row">
    <div class="col-12 col-sm-6 col-md-6 col-lg-6">
      <% if @booking.mission.remaining_places > 0 %>
        <div class="mission-couv  " style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
          <div class="mission-banner" style="background-image: url(<%= cl_image_path(@booking.mission.picture, width: 377, height: 200, crop: :fill) %>);"><%= display_picto_cause(@booking.mission.cause) %>
                <div class="card-count-places">
                    <p><%= @booking.mission.remaining_places %></p>
                    <h3><%= label_for_remaining_places(@booking.mission.remaining_places) %></h3>
                </div>
          </div>
        </div>
      <% else %>
        <div class="mission-full" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
          <div class="mission-banner" style="background-image: url(<%= cl_image_path(@booking.mission.picture, width: 377, height: 200, crop: :fill,) %>);"><%= display_picto_cause(@booking.mission.cause) %>
              <div class="mission_banner-abort">
                <p>Cette mission est complète ! </p>
              </div>
          </div>
        </div>
      <% end %>
      <div class="mission-details">
        <h4><%= @booking.mission.cause.upcase %></h4>
        <h3><%= @booking.mission.title %></h3>
        <p><%=  @booking.mission.description %></p>
      </div>
      <div class="mission-infos">
        <h4>INFORMATIONS</h4>
          <div class="datetime">
            <div class="datetime-logo">
              <i class="far fa-calendar-alt"></i>
            </div>
            <p><%=@booking.mission.datetime.strftime("%d.%m.%Y à %HH%M") %></p>
          </div>
          <div class="duration">
            <div class="duration-logo">
              <i class="fas fa-history"></i>
            </div>
            <p><%=@booking.mission.duration %> H</p>
          </div>
        <div class="address">
          <div class="address-logo">
            <i class="fas fa-map-marker-alt"></i>
          </div>
          <p><%=@booking.mission.address %></p>
        </div>
      </div>
      <div class="association-details">
        <h4>PARTENAIRE</h4>
        <h3><%= @partner.name %></h3>
        <div class="alignement-description-logo">
          <%= cl_image_tag @partner.logo, crop: :thumb, gravity: :face, width: 40, height: 40, class: "avatar-large partner-logo" %>
          <p><%= @partner.description %></p>
        </div>
      </div>

      <div class="mission-infos">
        <h3>Votre supernova </h3>
          <p>
            <button class="btn btn-question-mark" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><i class="fas fa-question-circle"></i>
            </button>
          </p>
          <div class="collapse" id="collapseExample">
            <div class="card card-body">
              <p>
                Votre <b>supernova</b> qu’est ce que c’est ?
                <br>
                <br>
                C’est <b>LE bénévole référent</b> présent sur une action pour faire du lien entre les bénévoles, le partenaire et Benenova.
              </p>
            </div>
          </div>
          <div class="supernova">
            <p>
              <strong><%= @booking.mission.supernova.first_name %>
              <%= @booking.mission.supernova.last_name %> :</strong>
              <%= number_to_phone(@booking.mission.supernova.phone_number, delimiter: ' ', pattern: /(\d{2})/) %>
            </p>
          </div>
      </div>
      <button type="button" class="btn btn-primary cancel" data-toggle="modal" data-target="#exampleModalLong">
        Je souhaite annuler
      </button>

      <div class="col-12 col-sm-6 col-md-6 col-lg-6">
        <div class="show-map" style="height: 100%">
          <div
            id="map"
            style="width: 100%;
            height: 100%;
            min-height: 250px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
  </div>
</div>

<!-- Modal contact supernova en cas d'annulation -->

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <button type="button" class="close croix" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="modal-footer">
        <p>
          Es-tu sûr sûr sûr de vouloir annuler?
        </p>
        <button type="button" class="btn btn-primary non" data-dismiss="modal">Non</button>
        <%= link_to "Oui", cancel_dashboard_booking_path(@booking), class: "btn btn-info oui", method: :patch %>
      </div>
      <div class="modal-body">
        <p>
          <strong>Si oui, n’oublies pas de prévenir ton Supernova.</strong>
          <br>
            <%= @booking.mission.supernova.first_name %>
            <%= @booking.mission.supernova.last_name %> :
            <%= number_to_phone(@booking.mission.supernova.phone_number, delimiter: ' ', pattern: /(\d{2})/) %>
        </p>
      </div>
    </div>
  </div>
</div>

<!-- MAP -->
<!-- <br>
<div
  id="map"
  style="width: 100%;
  height: 250px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div> -->