config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :missions, only:[:show, :index] do
    resources :bookings, only:[:create]
  end

  get "/dashboard", to: "users#dashboard"
  namespace :dashboard do
    resources :bookings, only: :show do
      member do
        patch "cancel"
      end
    end
  end


  # resource :dashboard, only: :show
  # => GET   /dashboard(.:format)   dashboards#show

  # resources :bookings, only: []

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :bookings, dependent: :destroy
  has_many :missions, through: :bookings
  has_many :supernova_missions, foreign_key: "supernova_id", class_name: "Mission"

  # validates :first_name, uniqueness: { scope: :last_name }
  # validates :last_name, presence: true
  # validates :address, uniqueness: true, presence: true
  # validates :email, uniqueness: true, presence: true
  # validates :birth, uniqueness: true, presence: true
  # validates :phone_number, uniqueness: true, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @bookings = current_user.bookings
    @bookings_realised = current_user.bookings.joins(:mission).where("missions.datetime < ?", Date.today).order(datetime: :asc)
    @bookings_to_come = current_user.bookings.joins(:mission).where("missions.datetime >= ?", Date.today).order(datetime: :asc)
  end
end

app/views/users/_mission.html.erb
<%= link_to dashboard_booking_path(booking) do %>
  <div class="card-mission <%= 'canceled' if booking.status == 'declined' %>">
    <% if booking.status == 'declined' %>
      <div class="canceled-mission">
        <p>
          Annulée
        </p>
      </div>
    <% end %>
    <div class="card-picture" style="background-image: url(<%= cl_image_path(booking.mission.picture, height: 200, crop: :fill) %>);">
      <%= display_picto_cause(booking.mission.cause) %>
      <div class="card-count-places">
        <p><%= booking.mission.remaining_places %></p>
        <h3><%= label_for_remaining_places(booking.mission.remaining_places) %></h3>
      </div>
    </div>
    <div class="card-misson-infos">
      <div>
        <h4><%= display_date(booking.mission.datetime, booking.mission.duration) %></h4>
        <h2><%= booking.mission.title.capitalize %></h2>
        <p><%= booking.mission.description.capitalize %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<div class ="container-fluid">
   <h3>Mes missions</h3>
   <p>Voici le récapitulatif des missions auxquelles tu t'es engagé(e).</p>
</div>

<!-- PARTIAL -->





<% if params[:booking_created] %>
  <!-- <button type="button" class="btn btn-primary non" data-dismiss="modal">Non</button> -->
  <%#= link_to "Oui", mission_bookings_path(@mission), class: "btn btn-info oui", method: :post %>
    <!-- <div class="col-12 col-sm-6 col-md-4 col-lg-3"> -->
  <%= render 'shared/modal' %>
    <!-- </div> -->
<% end %>








<div class="cards-container">
    <div class="cards">
      <div class="row">
        <div class="col-12 col-sm-6 col-md-6 col-lg-6">
          <div class="missions-to-come-realised">
            <nav>
              <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">A venir</a>
                <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Réalisées</a>
              </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                <% @bookings_to_come.each do |booking_to_come| %>
                  <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <%= render 'users/mission', booking: booking_to_come %>
                  </div>
                <% end %>
              </div>
              <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                <% @bookings_realised.each do |booking_realised| %>
                  <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <%= render 'users/mission', booking: booking_realised %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>