config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :missions, only:[:show, :index] do
    resources :bookings, only:[:create]
  end

  get "/dashboard", to: "users#dashboard"
  namespace :dashboard do
    resources :bookings, only: :show do
      member do
        patch "cancel"
      end
    end
  end


  # resource :dashboard, only: :show
  # => GET   /dashboard(.:format)   dashboards#show

  # resources :bookings, only: []

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form_filters.html.erb
<%= form_tag missions_path, method: :get do %>

  <div class="field-block-dates">
    <div class="field-label">
      <%= label_tag(:starting_date, "Dates") %>
    </div>

    <div class="dates-start-end">
      <div class="dates">
          <%= date_field_tag :starting_date,
                             params[:starting_date],
                             class: "date-field"
          %>
        <label for="starting_date" id="starting_date_label">
          <div class="date-fullday">
          </div>
          <div class="date-day-and-month">
          </div>
        </label>
      </div>
      <div class="dates">
          <%= date_field_tag :ending_date,
                             params[:ending_date],
                             class: "date-field"
          %>
        <label for="ending_date" id="ending_date_label">
          <div class="date-fullday">
          </div>
          <div class="date-day-and-month">
          </div>
        </label>
      </div>
    </div>
  </div>

  <div class="field-block">
    <div class="field-label">
      <%= label_tag(:address, "Adresse") %>
    </div>
    <%= text_field_tag :address,
      params[:address],
      class: "form-control",
      placeholder: "Adresse"
    %>
  </div>

  <div class="field-block">
    <div class="field-label">
      <%= label_tag(:radius, "Dans un rayon de") %>
    </div>
    <div class="radius-text">
      <p>0km</p>
      <p>50km</p>
    </div>
    <%= range_field_tag :radius,
      params[:radius],
      # class: "form-control",
      placeholder: "Dans un rayon de",
      class: "custom-range",
      name: "radius",
      min: "0",
      max: "50",
      step: "5"
    %>
    <div class="radius-value">

      <% (5..45).step(5).each do |step| %>
        <% active_class = params[:radius].to_i == step ? "radius-on" : "" %>
        <p data-radius-value="<%= step %>" class="<%= active_class %>"><%= step %></p>
      <% end %>
    </div>
  </div>

  <div class="field-block">
    <div class="field-label">
      <%= label_tag(:duration, "Pour une durée maximum de") %>
    </div>
    <div class="duration-text">
      <p>1h</p>
      <p>2h</p>
      <p>3h</p>
      <p>4h</p>
    </div>
    <%= range_field_tag :duration,
      params[:duration],
      class: "form-control",
      placeholder: "Dans un rayon de",
      class: "custom-range",
      name: "duration",
      min: "1",
      max: "4",
      step: "1"
    %>
  </div>






  <div class="field-block">
    <div class="field-label">
      <%= label_tag(:causes, "Cause(s)") %>
    </div>
      <div class="causes-container">
        <% Mission::CAUSES.each do |cause| %>
            <span class="cause-option">
              <%= check_box_tag 'causes[]', cause, params[:causes]&.include?(cause), id:'cause_' + cause.parameterize(separator:"_"), hidden: true %>
              <%= label_tag 'cause_' + cause.parameterize(separator:"_"), class: "picto-cause" do %>
                <%= render "shared/icons/#{cause.parameterize(separator:"_")}" %>
              <% end %>
              <p><%= cause %></p>
            </span>
        <% end %>
      </div>
  </div>

  <div>
    <button type="sumbit" class="btn btn-info confirm-filters">C'est parti !</button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_modal.html.erb
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <button type="button" class="close croix" data-dismiss="modal" aria-label="Close">
        <span class="croix" aria-hidden="true">&times;</span>
      </button>
      <div class="modal-body">
        <p>
          <strong>Super, merci pour ta participation !</strong>
          <hr>
          Tu vas recevoir un email avec les coordonnées de ton <b>Supernova</b> (ton interlocuteur privilégié).</div>
        </p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


  <%= link_to "benenova", root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
      <!-- <i class="fas fa-bars" style="color: $green; font-size:30px;"></i> -->
    </span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Rechercher une mission", missions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mes missions", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Editer mon profil", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Déconnexion", destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link"%>
        </li>
      <% end %>
    </ul>
  </div>
</div>